parameters:
    welp_mailjet.api.class: \Mailjet\Client
    welp_mailjet.contacts_list_synchronizer.class: Welp\MailjetBundle\Service\ContactsListSynchronizer
    welp_mailjet.event_callback_manager.class: Welp\MailjetBundle\Service\EventCallbackManager

services:
    welp_mailjet.api:
        class: "%welp_mailjet.api.class%"
        arguments: ["%welp_mailjet.api_key%", "%welp_mailjet.secret_key%"]

    welp_mailjet.service.contacts_list_synchronizer:
        class: "%welp_mailjet.contacts_list_synchronizer.class%"
        arguments:
            - "@welp_mailjet.api"

    welp_mailjet.service.event_callback_manager:
        class: "%welp_mailjet.event_callback_manager.class%"
        arguments:
            - "@welp_mailjet.api"
