parameters:
    welp_mailjet.api.class: \Mailjet\Client
    welp_mailjet.contacts_list_synchronizer.class: Welp\MailjetBundle\Service\ContactsListSynchronizer
    welp_mailjet.event_callback_manager.class: Welp\MailjetBundle\Service\EventCallbackManager
    welp_mailjet.contact_manager.class: Welp\MailjetBundle\Service\ContactManager
    welp_mailjet.contact_listener.class: Welp\MailjetBundle\Listener\ContactListener

services:
    welp_mailjet.api:
        class: "%welp_mailjet.api.class%"
        arguments: ["%welp_mailjet.api_key%", "%welp_mailjet.secret_key%"]

    swiftmailer.transport.eventdispatcher.welp_mailjet:
        class: Swift_Events_SimpleEventDispatcher

    swiftmailer.mailer.transport.welp_mailjet:
        alias: welp_mailjet
        class: Welp\MailjetSwiftMailer\SwiftMailer\MailjetTransport
        arguments:
            - "@swiftmailer.transport.eventdispatcher.welp_mailjet"
            - "%welp_mailjet.api_key%"
            - "%welp_mailjet.secret_key%"

    welp_mailjet.service.contacts_list_synchronizer:
        class: "%welp_mailjet.contacts_list_synchronizer.class%"
        arguments:
            - "@welp_mailjet.api"

    welp_mailjet.service.event_callback_manager:
        class: "%welp_mailjet.event_callback_manager.class%"
        arguments:
            - "@welp_mailjet.api"

    welp_mailjet.service.contact_manager:
        class: "%welp_mailjet.contact_manager.class%"
        arguments:
            - "@welp_mailjet.api"

    # Listener
    welp_mailjet.contact_listener:
        class: %welp_mailjet.contact_listener.class%
        arguments:
            - '@welp_mailjet.service.contact_manager'
        tags:
            - { name: kernel.event_listener, event: welp.mailjet.subscribe, method: onSubscribe }
            - { name: kernel.event_listener, event: welp.mailjet.unsubscribe, method: onUnsubscribe }
            - { name: kernel.event_listener, event: welp.mailjet.update, method: onUpdate }
            - { name: kernel.event_listener, event: welp.mailjet.delete, method: onDelete }
            #- { name: kernel.event_listener, event: welp.mailjet.change_email, method: onChangeEmail }
